name: my_frist_githubaction_pipeline

on:
  push:
    branches:
      - main

# on:
#   workflow_dispatch

env:
  cloud: google-cloud

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: single line comment
        run: echo "Welcome to GithubActions" 
        env:
          Greeting: santh
      
      - name: multiline comment
        run: |
          echo "Welcome to multline comment"
          echo "This is for demo purpose only"
          echo "hello $Greeting is using $cloud"