name: my_frist_githubaction_pipeline

on:
  push:
    branches:
      - main

# on:
#   workflow_dispatch

env:
  cloud: google-cloud

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
          Greeting: santh
    steps:
      - name: single line comment
        run: echo "Welcome to GithubActions" 
        
      - name: multiline comment
        run: |
          echo "repository name: ${{ github.repository }}"
          echo "Welcome to multline comment"
          echo "This is for demo purpose only"
          echo "hello $Greeting is using $cloud with ${{ vars.PROJECT_ID }}"
      
      - name: Dump all github context
        run: echo '${{ toJson(github) }}'
