name: my_frist_githubaction_pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: single line comment
        run: echo "Welcome to GithubActions" 
      
      - name: multiline comment
        run: |
          echo "Welcome to multline comment"
          echo "This is for demo purpose only"